locations = ['USA', 'Great Britain', 'New Zealand, Poland', 'Spain, Vietnam']
print(locations)
print('----------------------')
print(sorted(locations))
print(locations)
print('----------------------')
print(sorted(locations, reverse=True))
print(locations)
print('----------------------')
locations.reverse()
print(locations)
print('----------------------')
locations.reverse()
print(locations)
print('----------------------')
locations.sort()
print(locations)
print('----------------------')
locations.sort(reverse=True)
print(locations)
print('----------------------')